### ISSUE TITLE
Choice of parser..

### ISSUE THREAD

**Issue by donquixote** [goaop/parser-reflection#1]
https://github.com/Roave/BetterReflection/issues/18#issuecomment-162223866

I had a quick look at the library (the README only).
So you are using nikic's php-parser library.

I was doing the same, but I have the impression that it is too big and does more than what is typically needed for reflection.
I also looked at some of the class files, and they seemed really big and hard to read.

On the other hand, I am a big fan of the "parser combinator" concept, which allows for much simpler classes.
https://github.com/Vektah/parser-combinator
https://github.com/ferno/loco/tree/v2 (really, look at the v2 branch, not at master!)

Of course one problem is that PHP has quite a complex grammar, with a lot of special cases. Using a combinator, the grammar definition would become quite nasty.
But for the reflection use case, we don't really need all this.

---------

Starting with token_get_all(), it should be possible to parse only the stuff that we are interested in (declaration of namespaces, use statements, functions, classes), and skip the rest (assignments, mathematical expressions, conditionals, loops, function calls, entire function and method bodies..). E.g. for method bodies, we only need to count the opening and closing curly brackets, to detect the end of the method body.

To save memory and computation time, we simply work with the same original $tokens array from token_get_all(), and pass it around all over the place. We avoid array slicing and manipulation, and we avoid unnecessary string operations. Most of the time, we only do array lookups by index.

The AST node for a method body would simply be a "lazy/proxy method body" object, which only has an unmodified copy of the full $tokens array, and the index where it begins. Same for expressions we choose to ignore.

One observation I made is that every "phrase" in PHP (not sure what's the correct term) ends either in a semicolon, or in a pair of curly brackets with something or nothing inside. The only exception I could think of is `do {..} while (..);` But this is fine if we simply regard this as two separate phrases, for simplicity.

Well, there is `?> .. <?php`. Ok. Let's just ignore it for now :)

So, for every "phrase", we:
- Skip all comment and whitespace at the beginning.
- Check if we find one of T_NAMESPACE, T_ABSTRACT, T_CLASS, T_FUNCTION and some others.
  - If yes, call the respective sub-parser.
  - If no, call the "ignore stuff" parser, which skips everything up to the next `;` or `{..}`.

This requires a "recursive ignore curly" sub-parser, which is quite easy to write.

So far my parser interface looks like this:

```php
interface PtkParserInterface {

  /**
   * @param array $tokens
   *   The tokens from token_get_all()
   * @param int $i
   *   Before: Position of the first token of the element to parse.
   *   After, success: Position of the first token _after_ the parsed element.
   *   After, failure: Same as before.
   * @param int $n
   *   Number of tokens in $tokens.
   *
   * @return mixed|false|null
   *   FALSE, if this parser does not match.
   *   NULL, if the parsed element can be skipped in the result.
   *   A parse subtree, otherwise.
   *
   * @throws ParseError
   *   If a syntax error is found in the code.
   *
   * @see token_get_all()
   */
  function parse(array $tokens, &$i, $n);

}
```

vektah instead uses an Input class to wrap the string, the index and length.

But both vektah and Loco work with a long string instead of tokens. This is fine, but it makes it harder to ignorantly skip parts of the input.

**Comment by donquixote** [comment]
> One observation I made is that every "phrase" in PHP (not sure what's the correct term) ends either in a semicolon, or in a pair of curly brackets with something or nothing inside.

And this even applies within a class body!

**Comment by lisachenko** [comment]
Hello one more time! Thank you for writing your thoughts about library.  I think that parsing time is not a critical one part of reflection library (who says that this should be fast), of course, fast parsing is a nice thing. We can try to open an issue for PHP-Parser itself to specify only interesting parts of AST to parse, for example white-list of structures (classes, methods, arguments, namespaces, etc) and optionally, method bodies, expressions.

Earlier I use https://github.com/Andrewsville/PHP-Token-Reflection, it was quite good and was able to analyze only important structures to work faster, but now it isn't maintained anymore. I want to rely on something more stable and maintainable, so PHP-Parser is one of the best components for that.

**Comment by lisachenko** [comment]
Also I may need to analyze expressions for method bodies too for my aspect-oriented framework (e.g. to intercept `include` or `require` constructions in the source code).

**Comment by donquixote** [comment]
Just for the conversation: I crafted my own parser reflection..
https://github.com/donquixote/hasty-reflection-parser

**Comment by lisachenko** [comment]
This year will be reflection libraries year :) Population of libraries increased by +3 /cc @Ocramius @asgrim

**Comment by lisachenko** [comment]
Closing this, because things won't be changed.
