### ISSUE TITLE
Add support for Symfony locator

### ISSUE THREAD

**Issue by hason** [goaop/parser-reflection#10]
We would like use this library in Symfony framework https://github.com/symfony/symfony/pull/18578

**Comment by lisachenko** [comment]
If I understood correctly, you want to replace https://github.com/goaop/parser-reflection/blob/master/src/LocatorInterface.php with Symfony's ResourceLocator one? Right?

**Comment by hason** [comment]
No, I want to add new locator
```php
namespace Go\ParserReflection\Locator;

use Symfony\Component\ClassLoader\ClassLoader;

class SymfonyLocator implements LocatorInterface
{
    /**
     * @var ClassLoader
     */
    private $loader;
    public function __construct(ClassLoader $loader = null)
    {
        if (!$loader) {
            $loaders = spl_autoload_functions();
            foreach ($loaders as $loader) {
                if (is_array($loader) && $loader[0] instanceof ClassLoader) {
                    $loader = $loader[0];
                    break;
                }
            }
            if (!$loader) {
                throw new ReflectionException("Can not found a correct composer loader");
            }
        }
        $this->loader = $loader;
    }
    /**
     * Returns a path to the file for given class name
     *
     * @param string $className Name of the class
     *
     * @return string|false Path to the file with given class or false if not found
     */
    public function locateClass($className)
    {
        return $this->loader->findFile($className);
    }
}
```

or refactor `ComposerLocator`

namespace Go\ParserReflection\Locator;

use Symfony\Component\ClassLoader\ClassLoader;

class BaseLocator implements LocatorInterface
{
    private $loader;
    public function __construct($loader = null)
    {
        if (!$loader) {
            $loaders = spl_autoload_functions();
            foreach ($loaders as $loader) {
                if (is_array($loader) && method_exists($loader[0], 'findFile')) {
                    $loader = $loader[0];
                    break;
                }
            }
            if (!$loader || !method_exists($loader[0], 'findFile')) {
                throw new ReflectionException("Can not found a correct loader with method 'findFile'");
            }
        }
        $this->loader = $loader;
    }
    /**
     * Returns a path to the file for given class name
     *
     * @param string $className Name of the class
     *
     * @return string|false Path to the file with given class or false if not found
     */
    public function locateClass($className)
    {
        return $this->loader->findFile($className);
    }
}
```

**Comment by lisachenko** [comment]
I'd prefer to choose your second variant, because it's universal and can be reused later for different projects.

**Comment by lisachenko** [comment]
No needed anymore, thanks to @nicolas-grekas and autoloader exception trick.
