### ISSUE TITLE
PHP 7.4 status

### ISSUE THREAD

**Issue by rulatir** [goaop/parser-reflection#102]
Is it true that this library can only reflect on PHP code up to PHP 7.3, or is this just an omission in the README?

**Comment by lisachenko** [comment]
Yes, previously it wasn't compatible with PHP7.4 as code wasn't updated for that. 2.x branch (and master) should be compatible with PHP7.4 now.

But I would like to suggest to switch to the BetterReflection library, as it maintained more.

**Comment by lisachenko** [comment]
Basic support for PHP7.4 was achieved in 2.1.2 patch version.
