### ISSUE TITLE
Incorrect reporting of endTokenPos attribute in recent versions of nikic/php-parser library.

### ISSUE THREAD

**Issue by lisachenko** [goaop/parser-reflection#104]
There are several bug reports in `goaop` framework itself about breaks in code:

https://github.com/goaop/framework/issues/451, 
https://github.com/goaop/framework/issues/452.

Need to release a hotfix patch version to prevent installation of broken versions.
@NikiC, ping

**Comment by nikic** [comment]
PHP-Parser 4.7.0 canonicalizes token_get_all() output to the PHP 8 format, using T_NAME_* tokens. Does that sound like something that could affect you? E.g. are you using token positions from PHP-Parser, but doing your own token_get_all call?

**Comment by lisachenko** [comment]
@nikic From what I can see, php-parser reports incorrect position of tokens for nodes. And I'm heavily use this information to adjust original source code (eg to find position where code should be changed). I'm using plain `token_get_all()` and information from php-parser to find correct position for node in token stream.

Am I right that indexes reported by php-parser can be used to specify an index for array returned by the `token_get_all()` for the same file?

**Comment by nikic** [comment]
@lisachenko The token positions returned by php-parser refer to positions into the tokens returned by `$lexer->getTokens()`, which are based on `token_get_all()`, but not exactly the same, due to some normalization of PHP version differences. Probably the 4.7 release was the first one where the difference became visible for your usage.

**Comment by lisachenko** [comment]
Ok, @nikic! Thanks for the quick response, I should update my code to follow new logic.

**Comment by xfuturomax** [comment]
@lisachenko is there any news or plans about using new version of php-parser? I want to upgrade my phpunit to version 9, an it requires ["nikic/php-parser": "^4.8"](https://github.com/sebastianbergmann/php-code-coverage/blob/master/composer.json#L35)

**Comment by lisachenko** [comment]
@xfuturomax unfortunately, I’m busy now with my new job, thus no time for open-source now. If you want - you can contribute this, it shouldn’t be very hard to adopt new version, need only to use proper methods instead of `get_tokens_all()` function call.

**Comment by xfuturomax** [comment]
https://github.com/goaop/framework/pull/454
https://github.com/goaop/parser-reflection/pull/106

I've tested with nikic/php-parser v4.10, and all code was generated correct.
