### ISSUE TITLE
docBlock Parser

### ISSUE THREAD

**Issue by onet4** [goaop/parser-reflection#11]
Hello,

Is there a plan to implement a docBlock parser supporting `{@inheritDoc}` and [docBlock templates](http://codingexplained.com/coding/php/how-to-use-docblock-templates-in-phpdoc) with `/**#@+` and `/**#@-*/` like outdated [PHP Token Reflection](https://github.com/Andrewsville/PHP-Token-Reflection) does?

Say there is code something like this,

```php
/**
 * This is a base class.
 */
class SomeBase {
    
    /**#@+
     * @return string
     * @since 1.0.0
     */
    /**
     * Prints the method name.
     */
    public function printMethodName() {
        return '';
    }
    
    /**
     * Returns the method name.
     */
    public function getMethodName() {
        return __METHOD__;
    }    
    /**#@-*/
    
}
 
/**
 * This is some class.
 * 
 * This is a sample class to test reflection methods.
 *
 */
class SomeClass extends SomeBase {
       
    /**
     * {@inheritDoc}
     */
    public function printMethodName() {
        echo $this->getMethodName();
    }
    
}
```

Then it would be great if we could retrieve the value of a specified annotation. 
```php
$parsedClass = new \Go\ParserReflection\ReflectionMethod('SomeClass', 'printMethodName');
var_dump($parsedClass->getAnnotation('return'));
```

**Comment by lisachenko** [comment]
Hello! 
I want this library to be as close to the internal reflection implementation as possible. And internal reflection doesn't support this version of doc-comments, actually they are looking weird :) 

So, I can confirm, that this library won't support this syntax. Reason is simple, imagine that we have a class that extends an internal one:

```php
class MySoap extends SoapClient
{
    /**#@+
     * @return string
     * @since 1.0.0
     */
    /**
     * Prints the method name.
     */
    public function printMethodName() {
        return '';
    }

    /**
     * Returns the method name.
     */
    public function getMethodName() {
        return __METHOD__;
    }    
    /**#@-*/    
}
```

If I call `(new ReflectionClass(MySoap::class))->getMethods()` then this array will consist of internal methods and extended. Internal methods won't have this functionality and parsed version will have, this will bring an inconsistency.

**Comment by onet4** [comment]
All right, thanks for answering.
