### ISSUE TITLE
Change PHP requirement to 5.4?

### ISSUE THREAD

**Issue by aik099** [goaop/parser-reflection#13]
Is is possible to change PHP version requirement to PHP 5.4?

I've found only 4 places (at least PhpStorm thinks so) that are using PHP 5.5+ features:

![2016-06-07_1227](https://cloud.githubusercontent.com/assets/1277526/15852789/2f840550-2cab-11e6-8f62-45553af8c9a3.png)
![2016-06-07_1226](https://cloud.githubusercontent.com/assets/1277526/15852790/2f9b7f0a-2cab-11e6-9587-9d517ba140bd.png)
![2016-06-07_1225](https://cloud.githubusercontent.com/assets/1277526/15852791/2fa69ae8-2cab-11e6-8f4c-67fb267f107e.png)
![2016-06-07_1224](https://cloud.githubusercontent.com/assets/1277526/15852792/2faae08a-2cab-11e6-9504-5165484981a0.png)

**Comment by lisachenko** [comment]
Hello, @aik099!

I don't have a plans to support an outdated versions of PHP. According to the [supported versions](http://php.net/supported-versions.php) only 5.6 and 7.x branches are supported now.

You should consider upgrading your software to the latest versions because even security fixes won't be available for 5.4 and even 5.5 version of PHP in one month.

**Comment by lisachenko** [comment]
PS. Still wondering, why do you use 5.4? I know, there was an issues for migration 5.3=>5.4, but 5.4=>5.5 or even 5.4=>5.6 is easy.

**Comment by aik099** [comment]
> PS. Still wondering, why do you use 5.4? I know, there were an issues for migration 5.3=>5.4, but 5.4=>5.5 or even 5.4=>5.6 is easy.

The only reason people don't support PHP 5.4 in their libraries, because officially it's EOL, but non officially a lot of people are using it and it costs $ for companies to upgrade all used software to work on supported PHP versions anyway.

> I don't have a plans to support an outdated versions of PHP. According to the supported versions only 5.6 and 7.x branches are supported now.

If I send a PR that adds PHP 5.4 support, then situation might change?

**Comment by lisachenko** [comment]
@aik099 but if you are supporting the old code, why suddenly do you need a library with modern functionality to be backported for oldest version? You can create your own fork of that library and apply your patch to it and just use it only for your own needs.

I can't see any valid points in backporting of old syntax into my library, so PR won't be accepted.

**Comment by aik099** [comment]
> @aik099 but if you are supporting the old code, why suddenly do you need a library with modern functionality to be backported for oldest version? 

Reflection API without autoloading reflected classes (that what this library is for) isn't a `modern functionality` as you call it. It's pretty standard functionality really. By comparing various libraries doing relatively same thing (use tokenizer and then map back to reflection classes) as yours I've found this one to be best in class. And after that the PHP 5.4 compatibility is the only thing standing between me and this library.

> I can't see any valid points in backporting of old syntax into my library, so PR won't be accepted.

There are only 4 lines of code (not counting tests) to be changed to make it PHP 5.4 compatible. By looking at them (see above screenshots) I haven't found any real benefits (e.g. works faster) from using PHP 5.5+ syntax. Adding PHP 5.4 support would in turn bring more users to the library.

**Comment by aik099** [comment]
Is cost of maintaining PHP 5.4 version support really that high, that you're not willing to support it?

**Comment by lisachenko** [comment]
I'm sorry, but the question is not in the price of maintaining this stuff, this is more related to the security and additional checks in the code for throwing an exception if current platform is not capable to handle this specific construction or method.

Downgrading the master branch to be 5.4 compatible (which is not supported any more) in any project is a bad idea, so, please be calm and respect MIT license rule or just fork it and make your own patched version for working with PHP5.4 version.

Hope, that you understood my position about keeping only supported versions of PHP.

**Comment by aik099** [comment]
I'll create a fork then. Clearly proposed changes doesn't introduce any security related issues anyway.
