### ISSUE TITLE
ReflectionException "Could not find handler (..) resolveExprUnaryMinus method" for parameters like $foo-

### ISSUE THREAD

**Issue by marcovtwout** [goaop/parser-reflection#140]
On latest `master`, when parsing a class method that has a signature like this:

```
public function bar($foo = -1)
```

An exception is thrown when processing the node for `$foo`:

```
Go\ParserReflection\ReflectionException : Could not find handler for the Go\ParserReflection\Resolver\NodeExpressionResolver::resolveExprUnaryMinus method
 \src\Resolver\NodeExpressionResolver.php:171
 \src\Resolver\NodeExpressionResolver.php:150
 \src\ReflectionParameter.php:104
```

The node is of type `PhpParser\Node\Expr\UnaryMinus`

**Comment by lisachenko** [comment]
Hm, nice, really missed this part

**Comment by alx-xc** [comment]
We have same problem (resolveExprUnaryMinus).
And another similar error: 
`Could not find handler for the Go\ParserReflection\Resolver\NodeExpressionResolver::resolveExprArrayDimFetch method `

**Comment by lisachenko** [comment]
Merged into the master branch support for the UnaryMinus/UnaryPlus expressions.

**Comment by lisachenko** [comment]
@alx-xc 
> We have same problem (resolveExprUnaryMinus).
And another similar error:
Could not find handler for the Go\ParserReflection\Resolver\NodeExpressionResolver::resolveExprArrayDimFetch method 

Could you please open a separate issue or send me a small PR for this (ideally with test) to merge into the main branch?
