### ISSUE TITLE
Helper methods for avoiding memory leaks

### ISSUE THREAD

**Issue by aik099** [goaop/parser-reflection#18]
The "\Go\ParserReflection\ReflectionEngine::parseClass" method is caching each processed file in `\Go\ParserReflection\ReflectionEngine::$parsedFiles` property. This is correct behavior and allows to avoid high CPU load, when parsing code base, when parsing classes, that extend few common classes.

However this behavior also leads to memory leak, when parsing lots of unrelated classes, because each of classes is parsed only once and after being parsed is never reused.

Proposing to add following methods, that would allow user to manually remove cached parsed file:

```php
/**
 * Removes parsing result of a file
 *
 * @param string      $fileName Name of the file
 *
 * @return void
 * @throws \InvalidArgumentException When file isn't parsed.
 */
public static function unsetFile($fileName)
{
    if (!isset(self::$parsedFiles[$fileName])) {
        throw new \InvalidArgumentException('The "' . $fileName . '" isn\'t parsed.');
    }

    unset(self::$parsedFiles[$fileName]);
}
```

**Comment by aik099** [comment]
I can send a PR if you'd like.

**Comment by aik099** [comment]
I've found that it's much faster to control memory usage this way instead of trying to parse large code bases using parallel processes.

**Comment by lisachenko** [comment]
Actually, I know about this limitation, but I think that instead of providing an API for unsetting items in the cache, it will be better to limit the overall number of cached items in the cache and make this configurable.

By default, it can have unlimited number of items in the cache, but if a specific option is set for `ReflectionEngine` class then kernel will keep only allowed number of items. 

Pseudo code will be something like that:
```php
if (isset(self::$maximumCachedFiles) && (count(self::$parsedFiles) === self::$maximumCachedFiles)) {
    array_shift(self::$parsedFiles);
}
self::$parsedFiles[] = // new file to insert
```

**Comment by aik099** [comment]
Another problem I've found, that is preventing configuration of `ReflectionEngine` is that it:

* is initialized with hardcoded locator class
* no way initialize it where needed, because Composer always does it upfront even if library isn't ever used during a particular script run

**Comment by lisachenko** [comment]
It's possible to reconfigure ReflectionEngine class with another instance of locator. Current way with automatic initialization typically covers ~90% cases of usage, thanks to the Composer. I want to hide `ReflectionEngine` class as an implementation detail, it will be nice if developers can use classes without additional configuration, but for 10% of missing cases it will be ok to reconfigure `ReflectionEngine` class

**Comment by aik099** [comment]
> It's possible to reconfigure ReflectionEngine class with another instance of locator.

You mean by calling `ReflectionEngine::init(...)` again with different locator?

> Current way with automatic initialization typically covers ~90% cases of usage, thanks to the Composer.

You mean, when:

* library is used within a project that you want to analyze
* project uses Composer as the only autoloader

?

In my case I wanted to analyze another project code and it was using a custom autoloader.

> I want to hide ReflectionEngine class as an implementation detail, it will be nice if developers can use classes without additional configuration, but for 10% of missing cases it will be ok to reconfigure ReflectionEngine class.

We're all developers after all. It's ok to do some little initialization, like `ReflectionEngine::init(new ComposerLocator())`. This way developer at least knows that library would be initialized at this point.

**Comment by lisachenko** [comment]
> You mean by calling `ReflectionEngine::init(...)` again with different locator?

Yes, correct.

> You mean, when:
- library is used within a project that you want to analyze
- project uses Composer as the only autoloader

Yes, it's typical case of usage, or I hope so :)

> In my case I wanted to analyze another project code and it was using a custom autoloader.

It's ok, you can init engine as you wish with your `ClassLocator` implementation.

Let's restrict this issue only to ability to clean items from the memory cache, this should be easy to implement and I'll be happy to accept a PR with implementation of limiting the number of items in the memory cache.

**Comment by aik099** [comment]
> https://github.com/goaop/parser-reflection/issues/18#issuecomment-225448686

Ah, now I see that you limit amount of parsed files in a buffer. So if buffer gets too busy you clean that buffer up and allow it to fill again. Yes, this solution looks like one, that can be pretty clever memory-consumption wise as automatic solution could be.

I'll send a PR then.
