### ISSUE TITLE
Support for non-Composer-based class locator

### ISSUE THREAD

**Issue by aik099** [goaop/parser-reflection#19]
In a project I'm analyzing 2 autoloaders are being used in combination. To cover that case I've created `CallableLoader`, that accepts any callback in constructor and will call it to locate class file.

If you're ok I can submit a PR with it.

**Comment by lisachenko** [comment]
Hi, this could be a nice addition for supporting non-composer projects. Please send a PR with `CallableLoader`

**Comment by aik099** [comment]
PR created, ready for review. I've named class `CallableLocator` (not `CallableLoader` as you said), because existing locator (`ComposerLocator`) is ending with `Locator` as well.

**Comment by lisachenko** [comment]
Merged
