### ISSUE TITLE
Fatal error, when using "self" or "parent" as method parameter type hint

### ISSUE THREAD

**Issue by aik099** [goaop/parser-reflection#23]
Not sure why, but PHP-Parser doesn't resolve `self` or `parent` to actual FQCN when used as class method parameter type hint. That results in exception with `Can not resolve a class name for parameter` message being thrown.

The `\Go\ParserReflection\ValueResolver\NodeExpressionResolver::fetchReflectionClass` should have taken care about that, but it didn't or it's not working for parameter type hints, but it's used only for resolving default value of parameter.

**Comment by lisachenko** [comment]
Fixed by PR, thanks!
