### ISSUE TITLE
Collect constants in a file defined via the "define" function

### ISSUE THREAD

**Issue by aik099** [goaop/parser-reflection#32]
The `\Go\ParserReflection\ReflectionFileNamespace::getConstants` - method would return constants defined in a namespace (e.g. `const NAME = 'value';`) and not ones defined in a file defined in a file (e.g. `define('CONSTANT_NAME', 'value')`).

The `\Go\ParserReflection\ReflectionFileNamespace::getFunctions` method on the other hand properly returns functions defined in a file.

**Comment by aik099** [comment]
Probably this can be implemented as `\Go\ParserReflection\ReflectionFileNamespace::getGlobalConstants` method, that will:

* iterate over top level `FuncCall` nodes
* if function name called is `define`, then:
 * take constant name from 1st argument
 * transform 2nd argument into a string using same resolver as used in `getConstants` method currently

**Comment by lisachenko** [comment]
Hi! This is very questionable issue, because the `define` operator can contain any dynamic expression, moreover it can be surrounded with if..else:
```php
if (mt_rand() > 0.5) {
    define('A', 1);
} else {
    define('A', 2);
}
```

I think that we shouldn't try to parse all defines in the namespace. But we can discuss this.

**Comment by aik099** [comment]
> ... ,because the define operator can contain any dynamic expression, ...

I myself use `define('TIMENOW', time());` code. Probably best approach here would be not attempting to resolve any code at all, but just return PHP fragment used to define constant (e.g. `time()` in above case).

> ... moreover it can be surrounded with if..else:

And we can also define constants in a while loop. If constant name can't be dynamic then we can just replace definition of previously found constant with same name.

Nowadays people use class constants instead of `define(...` statements and that's good. But when it comes preserving BC old `define(...` statements just can't be removed.

**Comment by lisachenko** [comment]
Just decided, that for the parser reflection we can't allow dynamic expressions, because they can call methods, objects, etc.

Why do you need a support for `define` constructions? Is it required or just a nice thing to have?

**Comment by aik099** [comment]
> Just decided, that for the parser reflection we can't allow dynamic expressions, because they can call methods, objects, etc.

That's why I proposed not to evaluate constant value and leave it as PHP code. If needed whoever uses the library can `eval` that code.

> Why do you need a support for define constructions? Is it required or just a nice thing to have?

On a project that I'm creating I'm checking BC of 2 versions of any given app. As part of that check I'm verifying that constants defined in old app version are also present in new app version. In there I don't really care about constant value because constant name is used in actual code and not its value.

**Comment by lisachenko** [comment]
> On a project that I'm creating I'm checking BC of 2 versions of any given app. As part of that check I'm verifying that constants defined in old app version are also present in new app version. In there I don't really care about constant value because constant name is used in actual code and not its value.

Ok, now I understood why do you need to parse all defines. However, searching for all `define` expressions is very expensive, is it ok? I think it will be ok to add a special binary flag in the `\Go\ParserReflection\ReflectionFileNamespace::getConstants(ReflectionFileNamespace::WITH_DEFINED_CONSTANTS)` and make it off by default.

So if we enable it, then all constants will be returned, both const and defined. If no then only constants that are declared via const

**Comment by aik099** [comment]
> However, searching for all define expressions is very expensive, is it ok?

We can cheat a bit in that aspect. We only look for top-level function calls in a file (as I suggested initially). Yes, that won't find us defines in IF statements, but will get us pretty much everything. If any of library users would approach and say that not all `defines` are found, then we'll improve/slow down that searching code later.

> I think it will be ok to add a special binary flag in the \Go\ParserReflection\ReflectionFileNamespace::getConstants(ReflectionFileNamespace::WITH_DEFINED_CONSTANTS) and make it off by default.
> So if we enable it, then all constants will be returned, both const and defined. If no then only constants that are declared via const

Sounds good.

**Comment by lisachenko** [comment]
> Sounds good.

Ok, let's proceed then :) Thank you very much for contributing!

**Comment by aik099** [comment]
This was quite a productive and on short discussion. For other projects, where I'm a maintainer, PR discussions tend to be 100+ comments.

**Comment by aik099** [comment]
PR #46 created and ready for review.
