### ISSUE TITLE
The "ReflectionEngine::setMaximumCachedFiles" doesn't reevaluate existing cache

### ISSUE THREAD

**Issue by aik099** [goaop/parser-reflection#35]
When `ReflectionEngine::setMaximumCachedFiles` method is called it currently only changes maximal allowed file count in cache. That's perfectly fine, when used prior to file parsing process is started.

Unfortunately, when used in the middle of process (e.g. when got high memory consumption I try to reduce cached file count), then nothing happens.

I expect existing cache to be sliced (from oldest to newest) to reduce cache to given size (or smaller if less files are cached, then requested).

**Comment by lisachenko** [comment]
This can be implemented in the setter, why not...
