### ISSUE TITLE
Cannot parse classes with conditional definition.

### ISSUE THREAD

**Issue by YLivay** [goaop/parser-reflection#41]
We are using AspectMock 2.0.0 which uses goaop/parser-reflection 1.1.0 to mock some classes for unit testing.

While mocking Stripe's library we received:
`InvalidArgumentException: Class Stripe\JsonSerializable was not found in the /path/to/vendor/stripe/stripe-php/lib/JsonSerializable.php in /path/to/vendor/goaop/parser-reflection/src/ReflectionEngine.php:144`

The problematic file:

``` <?php

namespace Stripe;

// JsonSerializable only exists in PHP 5.4+. Stub if out if it doesn't exist
if (interface_exists('\JsonSerializable', false)) {
    interface JsonSerializable extends \JsonSerializable
    {
    }
} else {
    // PSR2 wants each interface to have its own file.
    // @codingStandardsIgnoreStart
    interface JsonSerializable
    {
        // @codingStandardsIgnoreEnd
        public function jsonSerialize();
    }
}
```

After rewriting the file to the following, everything worked again:

``` <?php

namespace Stripe;

interface JsonSerializable extends \JsonSerializable
{
}
```

We are using PHP 7.

**Comment by lisachenko** [comment]
Hi, conditional classes are big pain for analysis :) Unfortunately, there is no easy way to analyse such complex cases.

What do your expect from parser-reflection, how it should work in such cases? What if I use `new Go\ParserReflection\ReflectionClass(Stripe\JsonSerializable::class)` which definition should be used?

**Comment by lisachenko** [comment]
It's almost impossible to implement this feature in correct way just by static analysis, so closing it...
