### ISSUE TITLE
Namespace \yii\base was not found in the file …/vendor/yiisoft/yii2/base/Application.php

### ISSUE THREAD

**Issue by zuozp8** [goaop/parser-reflection#42]
I got error
  [Go\ParserReflection\ReflectionException]                                                             
  Namespace \yii\base was not found in the file …/vendor/yiisoft/yii2/base/Application.php                                                                                           

It parser has problem when parsing mine `\CommonApplication` (code below) that required parsing `\yii2\base\Application`.

```
<?php
abstract class CommonApplication extends yii\base\Application
{
}
```

adding `\ ` after `extends` like `abstract class CommonApplication extends \yii\base\Application` solves the problem

i have parser-reflection@1.1.0

**Comment by lisachenko** [comment]
Hi, am I right that namespace for CommonApplication is global?

**Comment by zuozp8** [comment]
yes

**Comment by zuozp8** [comment]
```
PHP Fatal error:  Uncaught Go\ParserReflection\ReflectionException: Namespace \yii\base was not found in the file …/vendor/yiisoft/yii2/base/Application.php in …/vendor/goaop/parser-reflection/src/ReflectionEngine.php:247
Stack trace:
#0 …/vendor/goaop/parser-reflection/src/ReflectionEngine.php(133): Go\ParserReflection\ReflectionEngine::parseFileNamespace('...', '\\yii\\base')
#1 …/vendor/goaop/parser-reflection/src/ReflectionClass.php(45): Go\ParserReflection\ReflectionEngine::parseClass('\\yii\\base\\Appli...')
#2 …/vendor/goaop/parser-reflection/src/Traits/ReflectionClassLikeTrait.php(448): Go\ParserReflection\ReflectionClass->__construct('\\yii\\base\\Appli...')
#3 …/vendor/goaop/parser-reflection/src/Traits/ReflectionClassLikeTrait.php(917): Go\ParserReflection\ReflectionClass->getParentClass()
#4 …/vendor/goaop/parser-reflection/src/Traits/Reflect in …/vendor/goaop/parser-reflection/src/ReflectionEngine.php on line 247
```

**Comment by lisachenko** [comment]
Sorry, I'm busy now because of preparing for SymfonyCon conference, so, ping me after two weeks, I'll have a look, or even better if you can send a PR, I'll be happy to merge it.

**Comment by zuozp8** [comment]
Unfortunately I'm not able to find time to get familiar with the code and fix it myself. I'll remind you about this issue after some time.

**Comment by aik099** [comment]
@zuozp8 , can you please attach top of `…/vendor/yiisoft/yii2/base/Application.php` file, where namespace/class declarations are without actual class contents?

**Comment by zuozp8** [comment]
https://raw.githubusercontent.com/yiisoft/yii2/master/framework/base/Application.php
