### ISSUE TITLE
Issues with PHP 5.6's class constant expressions

### ISSUE THREAD

**Issue by pdelre** [goaop/parser-reflection#45]
I believe I've found a couple issues with support for PHP 5.6's class constant expressions (http://php.net/manual/en/language.oop5.constants.php#example-179).

The class below will cause a segfault as parsing goes into an infinite loop:

```php
class Foo {
    const MINUTE = 60;
    const HOUR = 3600;

    const DEFAULT = self::MINUTE;
}
```

I am able to create other errors by adding the following class to `tests/Stubs/FileWithClasses56.php` (pulled from php.net's page above).

```php
const ONE = 1

class ClassWithConstantExpressions
{
    // below constants cause assertion failures, but no segfaults
    const TWO = ONE * 2;
    const THREE = ONE + self::TWO;
    const SENTENCE = 'The value of THREE is '.self::THREE;

    // uncommenting below will cause a segfault
    // const DEFAULT = self::TWO;
}
```

Failing output:
```
PHPUnit 4.8.30 by Sebastian Bergmann and contributors.

...............................................................  63 / 148 ( 42%)
II.....................F....................................... 126 / 148 ( 85%)
......................

Time: 157 ms, Memory: 10.00MB

There was 1 failure:

1) Go\ParserReflection\ReflectionClassTest::testGettersPHP56
getConstants() for class Go\ParserReflection\Stub\ClassWithConstantExpressions should be equal
Failed asserting that Array &0 (
    'TWO' => null
    'THREE' => null
    'SENTENCE' => null
) is identical to Array &0 (
    'TWO' => 2
    'THREE' => 3
    'SENTENCE' => 'The value of THREE is 3'
).

/Users/pdelre/Projects/github/parser-reflection/tests/ReflectionClassTest.php:299
/Users/pdelre/Projects/github/parser-reflection/tests/ReflectionClassTest.php:175

FAILURES!
Tests: 148, Assertions: 1714, Failures: 1, Incomplete: 2.
```

segfault failure:
```
PHPUnit 4.8.30 by Sebastian Bergmann and contributors.

...............................................................  63 / 148 ( 42%)
II.....................[1]    45899 segmentation fault  vendor/bin/phpunit tests
```

**Comment by aik099** [comment]
You have shown 2 test runs. When does the segmentation fault happen?

**Comment by pdelre** [comment]
When the `ClassWithConstantExpressions::DEFAULT` is uncommented.

```php
const ONE = 1

class ClassWithConstantExpressions
{
    // below constants cause assertion failures, but no segfaults
    const TWO = ONE * 2;
    const THREE = ONE + self::TWO;
    const SENTENCE = 'The value of THREE is '.self::THREE;

    // uncommenting below will cause a segfault
    const DEFAULT = self::TWO;
}
```

I've figured out that the previous three const (`TWO`, `THREE`, `SENTENCE`) do not cause segfaults since there are no resolve methods for their node types (`resolveExprBinaryOpMul`, `resolveExprBinaryOpPlus`, `resolveExprBinaryOpConcat`).

Once I added those methods to `NodeExpressionResolver`, they will cause a segfault when attempting to resolve `self::TWO`/`self::THREE` but are fine resolving `\ONE`.

Currently unravelling `NodeExpressionResolver::resolveExprClassConstFetch` for the nodes containing `self`.

**Comment by lisachenko** [comment]
Hi, thank you for the report!

**Comment by lisachenko** [comment]
Should be solved now.

**Comment by pdelre** [comment]
Thanks. I missed the fact that I had below written but not POSTed yet. :/ Your solution for the `self::CONST` recursion is much more elegant.

--------

<strike>
I've pushed a branch to my fork replicating the errors in tests with an implemented solution. As I'm new to this project via a dependency of a dependency, I do not if resolving the binary operators is within the scope of the project or needed. Either way, the recursive resolution is hidden by binary operators.
<br/><br/>
In order to bypass the recursive parsing that <code>self</code> is triggering, I've exposed the constant <code>Node</code>s outside the <code>ReflectionClass</code> which feels wrong but I'm hoping the work here can help those with more intimate knowledge come to a proper solution or direction.
<br/><br/>
https://github.com/goaop/parser-reflection/compare/master...pdelre:issue-45-class-constant-expressions
</strike>

**Comment by lisachenko** [comment]
@pdelre you are welcome ) version 1.2.0 will be released soon
