### ISSUE TITLE
NodeExpressionResolver will attempt to Reflect system classes

### ISSUE THREAD

**Issue by pdelre** [goaop/parser-reflection#48]
There are cases where the `NodeExpressionResolver` is attempting to Reflect system classes.

For example, the following will fail tests with an `InvalidArgumentException(Class DateTime was not found by locator)` from `ReflectionEngine::locateClassFile`:

Stub/FileWithClasses56.php

```php
class ClassWithComplexConstantsAndInheritance extends ClassWithArrayConstants
{
    const K = array(1, NS_CONST56);
    const L = [self::class, ClassWithArrayConstants::A, parent::B];
    // addition
    const M = \DateTime::ATOM;
}
```

I've seen this occur with parameters in production code, but haven't been able to reproduce it in the test suite yet.

**Comment by lisachenko** [comment]
Thank you for contributing!
