### ISSUE TITLE
Readme example code causes an error

### ISSUE THREAD

**Issue by onet4** [goaop/parser-reflection#61]
It seems the usage example code in [README.md](https://github.com/goaop/parser-reflection/blob/1.1.0/README.md) has a glitch.

The line, `var_dump($fileNameSpaces[0]->getClass(SomeClass::class)->getMethods());`, causes the error `Fatal error: Call to a member function getClass() on null`. I guess a namespace name is set to the array key.

**Comment by aik099** [comment]
If you're seeing the error, then you can probably just tell what is the key by doing above line from README.md: the `var_dump($fileNameSpaces)`.

**Comment by onet4** [comment]
It seems `0` occurs when there is no namespace.

**Comment by lisachenko** [comment]
Key should be the namespace name or empty string for the global namespace code.

**Comment by aik099** [comment]
Then indeed example in README.md should be updated to avoid using `0` as key.

**Comment by onet4** [comment]
What about changing it to use `foreach()`?

```php
foreach($fileNameSpaces as $element) {
    var_dump($element->getClass(SomeClass::class)->getMethods());
}
```

But there are cases that the type is not the class. 

I'm not an expert here. Just hoping to see better examples.

**Comment by lisachenko** [comment]
Updated README

**Comment by onet4** [comment]
Looks better now. Thank you.
