### ISSUE TITLE
Fatal error: Class 'ReflectionType' not found 

### ISSUE THREAD

**Issue by onet4** [goaop/parser-reflection#62]
Hi,

I get the error `Fatal error: Class 'ReflectionType' not found in ...vendor\goaop\parser-reflection\src\ReflectionType.php on line 19` when trying to use the class. It even occurs when checking the class existence.

```php
class_exists('\Go\ParserReflection\ReflectionType');
```

Other classes including `ReflectionClass`, `ReflectionMethod`, `ReflectionFile` and `ReflectionFunction` are loaded just fine.

**Comment by lisachenko** [comment]
Hi, do you use the Composer in your project?

**Comment by lisachenko** [comment]
If you use version >=7.0 then `ReflectionType` should be available in your system, otherwise, composer will automatically include the [src/bootstrap.php](https://github.com/goaop/parser-reflection/blob/master/src/bootstrap.php) file with polyfill for the `ReflectionType`.

So, looks like you running library on PHP<7.0 without composer, am I right?

**Comment by onet4** [comment]
> So, looks like you running library on PHP<7.0 without composer, am I right?

No, I used composer. The content of the `composer.json` file is

```json
{
    "require": {
        "goaop/parser-reflection": "^1.1"
    }
}
```

I deleted the `composer.json`, `composer.lock` files and the `vendor` directory and reinstalled the dependencies by performing

```bash
composer require goaop/parser-reflection
```

But the result is the same.

PHP 5.6, Composer 1.3.0, Windows 7

**Comment by lisachenko** [comment]
Just checked your case and can confirm that version 1.1.0 doesn't contain the `ReflectionType` polyfill. So, I'm going to release 1.2.0 today with new features and fixes.

Thanks for reporting!

**Comment by onet4** [comment]
Works fine now.

**Comment by lisachenko** [comment]
Great! :+1:
