### ISSUE TITLE
Extra methods for parsing return/param type information from DocBlocks

### ISSUE THREAD

**Issue by aik099** [goaop/parser-reflection#65]
While looking at https://github.com/Roave/BetterReflection I've found an interesting feature: new methods added to `ReflectionFunction` and `ReflectionParameter` methods for getting type that was parsed from DocBlock of function/method.

This is done with the help of these packages:

* https://packagist.org/packages/phpdocumentor/reflection-docblock
* https://packagist.org/packages/phpdocumentor/type-resolver

I myself don't have any application for this right now, but might be a useful feature in general. For example for some analytical tool that checks incompatible DocBlock types for method overridden in sub-class in comparison to it's parent class.

**Comment by lisachenko** [comment]
This library tries to be as close to native reflection as possible. If someone wants, he could easily extend current framework classes with additional logic.
