### ISSUE TITLE
Fatal error in PHP nightly builds (7.2.0-dev)

### ISSUE THREAD

**Issue by ramsey** [goaop/parser-reflection#70]
In PHP nightly builds (PHP 7.2.0-dev) used on Travis CI, I'm receiving the following fatal error:

```
Declaration of Go\ParserReflection\Traits\ReflectionClassLikeTrait::newInstance($args = NULL) should be compatible with ReflectionClass::newInstance(...$args)

/home/travis/build/ramsey/uuid/vendor/goaop/parser-reflection/src/ReflectionClass.php:24
```

See here for details: https://travis-ci.org/ramsey/uuid/jobs/212487660

**Comment by lisachenko** [comment]
Hi, @ramsey!
Thank you for posting this issue, looks like it is a BC break in the PHP engine and I'm not sure that this should be ok.

Have you reported this to internals?

**Comment by ramsey** [comment]
@dshafik, @krakjoe: who are the release managers for 7.2? The wiki doesn't say. I want to run this by them first before reporting to make sure it's not already a known or expected issue.

**Comment by dshafik** [comment]
@ramsey there aren't any yet. A vote will be held at a later date to pick them. For now, just email internals.

**Comment by ramsey** [comment]
Thanks!

**Comment by ramsey** [comment]
Reported here: https://bugs.php.net/bug.php?id=74292

**Comment by loren-osborn** [comment]
&lt;lament&gt;
Not that you should have to for situations like this, but it's too bad you can't fixed-at/before-compile-time stuff like function signatures, base classes, interfaces, traits, method/property names and/or omission evaluable at compile-time. You can simply put the *whole class* in an `if` (which is at least a viable option for avoiding duplicate definitions), but you can't make elements within a class conditional, or parameterize anything compile-time. Just yesterday I had to stoop to an `eval()` to make a type-safe `curry()` function. &#x1f641; **Almost** makes you miss C macros. &#x1f609;
&lt;/lament&gt;

**Comment by lisachenko** [comment]
This bug was introduced in https://github.com/php/php-src/pull/2363 and later reverted in https://github.com/php/php-src/commit/eb1373e509a69a48e90e6dd4c2dda1348e19b776

Should work for PHP>=7.0.17, PHP>=7.1.3, PHP7.2@dev

Thank you @ramsey for reporting this issue 👍

**Comment by ramsey** [comment]
Good to here. Looks like no one has updated either of the tickets that reported this to the core yet.

**Comment by lisachenko** [comment]
Fixed with beautiful signature hack for all modern PHP verisons: https://3v4l.org/eeVf8.

Version 1.2.1 is released for that to avoid this annoying BC break.

**Comment by loren-osborn** [comment]
PHP 5.6 will accept `...$args` as a function parameter? I'm somewhat surprised.
