### ISSUE TITLE
Class \ClassName was not found by locator

### ISSUE THREAD

**Issue by VolCh** [goaop/parser-reflection#80]
The class exists in the top level (no namespaces) in src subdir, it presents in the composer classmap (without leading backslash), the application works fine, but codeception tests with aspectmock does not work:
```
  [InvalidArgumentException]               
  Class \ClassName was not found by locator  
                                           

Exception trace:
 () at /app/vendor/goaop/parser-reflection/src/ReflectionEngine.php:125
 Go\ParserReflection\ReflectionEngine::locateClassFile() at /app/vendor/goaop/parser-reflection/src/ReflectionEngine.php:140
 Go\ParserReflection\ReflectionEngine::parseClass() at /app/vendor/goaop/parser-reflection/src/ReflectionClass.php:44
...
```
PHP versions 5.6 and 7.1, parser-reflection 1.4.0

**Comment by VolCh** [comment]
I found workaround:
With line 125 of ReflectionEngine.php changed to 
```
            $classFileName = self::$locator->locateClass(ltrim($fullClassName, '\\'));
```
from 
```
            $classFileName = self::$locator->locateClass($fullClassName);
```
my tests work fine.

But I am not sure that it is correct way.

**Comment by daniel-sc** [comment]
I recognized the same thing - anyone working on this?

**Comment by aik099** [comment]
Yes, see #83 PR.

**Comment by alexglue** [comment]
damn, is it possible to fix (merge) this bug ? it is a critical issue!

**Comment by aik099** [comment]
I've asked this question on https://github.com/goaop/parser-reflection/pull/89 PR, that fixes this.
