### ISSUE TITLE
Bump  "nikic/php-parser": "^1.2|^2.0|^3.0", add ^4.0, if possible

### ISSUE THREAD

**Issue by TheCelavi** [goaop/parser-reflection#91]
SF 4 (web app) installs maker bundle, which requires nikic/php-parser ^4.0, and then we have a conflict...

If nikic/php-parser can be bumped to ^4.0 as well, all could be just fine.

Is it possible to do it safely ?

**Comment by aik099** [comment]
If you can do it safely, then please create a PR. I have no objections.

**Comment by TheCelavi** [comment]
Hahahhaha, of course - I thought that someone perhaps tested, NP, will do so, thanks.

Since there are tests, I guess there will be no problems to verify this..

**Comment by TheCelavi** [comment]
@aik099 Not possible, all tests fail. Nikita Popov added a lot of BC breaks with new version. Whole code base must be revised... :(

**Comment by TheCelavi** [comment]
https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-4.0.md

I do not think that it can be done safely, meaning, that it can support both ^3 and ^4 versions of Nikic's parser, I think that this library would require bumping of its version up...

**Comment by lisachenko** [comment]
Yes, this requires some work... 

Or just wait for `BetterReflection` maintainers to release a new tag and kill this repo, switching `goaop` framework itself to the BR 😆
I love this small library but lack of my free time and solid maintainers will result in stagnation...
