### ISSUE TITLE
Issues with ReflectionClass::getReflectionConstants()

### ISSUE THREAD

**Issue by kierany5** [goaop/parser-reflection#93]
I've been testing some functionality and while using getReflectionConstants() I get a fatal error.

**Test Class**
```php
<?php
class GlobalClass {
    public $test = true;

    public const PUBLIC_CONSTANT = 1;
    protected const PROTECTED_CONSTANT = 2;
    private const PRIVATE_CONST = 3;
}
```

**Test Script (modified for here)**
```php
<?php
require(__DIR__.'/../vendor/autoload.php');

$parsedFile = new \Go\ParserReflection\ReflectionFile(__DIR__.'/../testsrc/SimpleStructure/GlobalClass.php');

foreach($parsedFile->getFileNamespaces() as $namespace) {
    foreach($namespace->getClasses() as $class) {
        foreach($class->getReflectionConstants() as $constant) {
            var_dump($constant);
        }
    }
}
```

**Result/terminal output**
```
Fatal error: Uncaught Error: Internal error: Failed to retrieve the reflection object in constantsTest.php:17
Stack trace:
#0 constantsTest.php(17): ReflectionClass->getReflectionConstants()
#1 {main}
  thrown in constantsTest.php on line 17
PHP Fatal error:  Uncaught Error: Internal error: Failed to retrieve the reflection object in constantsTest.php:17
Stack trace:
#0 constantsTest.php(17): ReflectionClass->getReflectionConstants()
#1 {main}
  thrown in constantsTest.php on line 17
```

**PHP Version**
```
PHP 7.1.23 (cli) (built: Feb 22 2019 22:08:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

Using `getConstants()` works (returning an array with constant name and value) but this doesn't allow getting the visibility and other details of the constant.

Is there any word on whether this is a bug or a feature that hasn't been implemented.

**Comment by aik099** [comment]
This library emulates PHP reflection extension functionality using, static code analysis only (e.g. https://github.com/nikic/PHP-Parser). It does that for all of the PHP reflection methods, where it's possible.

The [getReflectionConstants](https://www.php.net/manual/en/reflectionclass.getreflectionconstants.php) method was only added in PHP 7.1.0 and wasn't yet ported to this library.

I see 2 options here:

* wait for this bug to be fixed OR send PR yourself
* switch to https://github.com/Roave/BetterReflection, which more actively maintained

Thank you.

**Comment by lisachenko** [comment]
Yes, I can confirm that this feature is not available at the moment.

**Comment by kierany5** [comment]
I'll come back to this issue at a later stage when I am less busy, if there is no word on updates I am more than happy to add my fair share.
