### ISSUE TITLE
Class parsing does not account for class_alias registrations

### ISSUE THREAD

**Issue by func0der** [goaop/parser-reflection#99]
https://github.com/goaop/parser-reflection/blob/6af734c8c9212d12317ae86e10dc22dd40c72f9a/src/ReflectionEngine.php#L133-L153

I am having a problem with this library in combination with this file or files like this especially: https://github.com/doctrine/persistence/blob/1.3.6/lib/Doctrine/Common/Persistence/ObjectRepository.php

It registers this file as the source of `Doctrine\Common\Persistence\ObjectRepository` in the composer class map.
But when it parses the file, it can not find the class inside of it, so it throws the `InvalidArgumentException`.

I am really struggeling on where to report this bug. Here, goaop/framework, doctrine/persistence.
I hope this was the right place for it.

Is this behavior somehow changeable?

**Comment by lisachenko** [comment]
Ugh, class aliasing is weird thing, unfortunately, parser reflection couldn't handle that because it doesn't evaluate the code. So, this exception should be caught somewhere and handled manually.

Maybe you have some ideas too?

**Comment by func0der** [comment]
If the parser would parse the whole file including that line `interface ObjectRepository extends \Doctrine\Persistence\ObjectRepository` in context of the namespace, it should still work, shouldn't it?

It would find the class `Doctrine\Common\Persistence\ObjectRepository` and that would solve the problem. I am not sure, why this is not happening, because the code is not evaluated but parsed, so the `if (false) {` should not be a non-issue, right?

**Comment by func0der** [comment]
@lisachenko ? Do you have an idea?

**Comment by lisachenko** [comment]
Unfortunately, I don’t have free time right now to work on this project. So if you can work on this and prepare PR, then it can be merged.

But class aliasing is not supported right now and I think it won’t be easy to add proper support as there can be several runtime classes, for example if random(10) > 5 then make class_alias to one class otherwise on another one.

**Comment by func0der** [comment]
If we rely on this premise of how to deprecate a type, i found an more than ugly fix for this problem: https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf

But it ain't ugly if it works, correct? ^^

**Comment by func0der** [comment]
I have created a repo to quickly reproduce the problem: https://github.com/func0der/reproduce-parser-reflection-problem
